# Source code for course work of Database System Design, 2012.09-11, Zhejiang University.
# By:
#   Shicheng XU(lightxuzju@gmail.com)
#   Xun LOU(AquarHEAD@gmail.com)
#   Pengyu CHEN(cpy.prefers.you@gmail.com)
# COPYLEFT, ALL WRONGS RESERVED.
#
#

all: *.go
	gccgo -c -o catman.o *.go

clean:
	rm -f catman.o
